name: Purge jsDelivr cache
on:
  push:
    branches:
      - main

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge marca-cta-pago.js cache
        run: |
          curl -X GET "https://purge.jsdelivr.net/gh/mensajego/MarcaDeAguaYCTA@main/marca-cta-pago.js"
          curl -X GET "https://purge.jsdelivr.net/gh/mensajego/MarcaDeAguaYCTA@main/marca-cta-free.js"
